DROP TABLE IF EXISTS kicks;

BEGIN;

CREATE TABLE kicks(
  kick_id SERIAL PRIMARY KEY,
  brand VARCHAR NOT NULL,
  img_url VARCHAR,
  price VARCHAR NOT NULL,
  year VARCHAR NOT NULL,
  size INT NOT NULL
);

CREATE TABLE users(
  user_id SERIAL PRIMARY KEY,
  username VARCHAR NOT NULL UNIQUE,
  password VARCHAR NOT NULL UNIQUE
);

COMMIT;
